# Colors (Paper Theme)

# Default colors
[colors.primary]
background = '#F6F2EE'
foreground = '#3D2B5A'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#CC3E28'
green   = '#216609'
yellow  = '#B58900'
blue    = '#1E6FCC'
magenta = '#5C21A5'
cyan    = '#158C86'
white   = '#AAAAAA'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#CC3E28'
green   = '#216609'
yellow  = '#B58900'
blue    = '#1E6FCC'
magenta = '#5C21A5'
cyan    = '#158C86'
white   = '#AAAAAA'
